


##AWS Fargate
cluster:
  name: eks-stag-poc

externalServices:
  prometheus:
    host: "http://dumy.monitoring.svc.cluster.local"
  loki:
    host: http://loki-loki-distributed-gateway.monitoring.svc.cluster.local

metrics:
  node-exporter:
    enabled: false

logs:
  pod_logs:
    gatherMethod: api

prometheus-node-exporter:
  enabled: false

alloy-logs:
  alloy:
    clustering: {enabled: true}
    mounts:
      varlog: false
  controller:
    replicas: 2
    type: deployment