cluster:
  name: qa-cluster
externalServices:
  prometheus:
    host: "http://mimir-nginx.monitoring.svc.cluster.local"
    writeEndpoint: /api/v1/push
    authMode: none
  loki:
    host: "http://loki-loki-distributed-gateway.monitoring.svc.cluster.local"
    authMode: none


opencost:
  enabled: false


prometheus-operator-crds:
  enabled: false
alloy: {}
alloy-logs: {}