kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-access-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-access-cluster-role-binding
subjects:
- kind: User
  name: k8s-access-user
roleRef:
  kind: ClusterRole
  name: k8s-access-cluster-role
  apiGroup: rbac.authorization.k8s.io