kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-dev-access-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-dev-access-cluster-role-binding
subjects:
- kind: User
  name: k8s-dev-access-user
roleRef:
  kind: ClusterRole
  name: k8s-dev-access-cluster-role
  apiGroup: rbac.authorization.k8s.io